[tool.poetry]
name = "na-sccwm"
version = "0.1.0"
description = ""
authors = ["Vineet Tiruvadi <virati@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.8.17"
dbspace = { path="/dbspace", develop=true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
