[project]
name = "cortical-signatures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "mayavi>=4.8.2",
    "mne>=1.9.0",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
]
